# Generated by Django 2.1.7 on 2019-02-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='userIDENTIFIER',
        ),
    ]
