# Generated by Django 2.1.7 on 2019-02-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20190223_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
